name: Linter

on: push

jobs:
  buld:
    runs-on: ubuntu-latest

    strategy:
      matrix:
      node-version: [14.x]

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # installing dependencies
      - name: install dependencies
        run: make install

      # Runs the Linter action
      - name: Run Linter
        run: make lint
